### ISSUE TITLE
Single Part In List

### ISSUE THREAD

**Issue by digimatt22** [Digi-Key/KiCad-Push-to-DigiKey#2] opened 2024-03-16 22:03 UTC
After installing the plugin and running it only a single part is listed.  I have tried changing the Part Number field but still only a single part is shown.  

V7.0.5-0, Release Build

**Comment by Walseth15** [comment] 2024-03-18 15:40
@digimatt22 Do you have a field with part numbers assigned to your symbols in the schematic editor?

**Comment by digimatt22** [comment] 2024-03-18 16:31
Yes I have a field MPN on all items. Do I need to change this field name?

**Comment by Walseth15** [comment] 2024-03-18 20:47
MPN should work fine.  Can you try opening your Symbol Fields Table (Tools >> Edit Symbol Fields) in the schematic editor and click "Apply, Save Schematic, and Continue"?

**Comment by digimatt22** [comment] 2024-03-19 13:29
It does the same thing, shows a single part. I changed to another field Digikey PN on each symbol and it again does the same thing, one part.

**Comment by Walseth15** [comment] 2024-03-19 14:09
I'm not able to reproduce the issue.  If you're interested, feel free to **[schedule a meeting](https://outlook.office365.com/owa/calendar/SchemeItInterviews@digikey.us/bookings/)** for us to talk through it.

**Comment by srbhjn11** [comment] 2024-08-14 11:13
I seem to be having same issue with KiCAD v8.0.4

**Comment by miranda** [comment] 2024-08-17 22:28
Same problem.  I can't get it to show anything but the first part number I assigned.

**Comment by Walseth15** [comment] 2024-09-13 21:38
@digimatt22 & @srbhjn11 - the plugin was skipping any parts within a hierarchical sheet and also missing some parts with multi-gated symbols.  These were both fixed in the [latest release](https://github.com/Digi-Key/KiCad-Push-to-DigiKey/releases).  Please give this a try and provide feedback if you're still having issues.

**Closed as completed** 2024-09-25 19:56 UTC
